// This will be  the base type for a meal without auto-generated properties
export interface BaseMeal {
    title: string;
    image: string;
    summary: string;
    instructions: string;
    creator: string;
};

// Use this when creating a new meal, before it has database-generated properties
export interface NewMeal extends BaseMeal {
    slug?: string; // slug can be optional because it can be generated from the title
};

// Use this type for meals that have been retrieved from the database, which will include an id and a slug
export interface Meal extends BaseMeal {
    id: number; // id is not optional here because it's generated by the database
    slug: string; // slug is not optional here because it's assumed to have been generated by the time you fetch the meal
};
